### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by AlexandreAndrade00** [ozaner/json_bigint#3]
Hello :grin: 

Can you update the package dependencies and publish the new version?

Thank you!

**Comment by ozaner** [comment]
Hey!
If you don't mind, could you tell me what dependencies do you want updated, and why? And also what versions you wanted them updated to? There are currently 2 dependencies: meta and petitparser.

**Comment by AlexandreAndrade00** [comment]
Update the meta for the flutter pinned version (1.15.0) and petitparser for the most recent stable. The other packages published on the pub.dev usually have the dependencies updated and the packages with old dependencies become incompatible. In my case, this package is incompatible with https://pub.dev/packages/json_path.

**Comment by ozaner** [comment]
Alright, I've weakened the dependency constraint on [`petitparser`](https://pub.dev/packages/petitparser) in the most recent version of the package v3.1.0:

`pubspec.yaml`

```diff
dependencies:
  meta: ^1.8.0
-  petitparser: ^5.1.0
+  petitparser: '>=5.1.0 <7.0.0'
```

I didn't change `meta`'s constraint because it already permits versions above `1.8.0` (e.g. `1.15.0`).
